name: backbone_env_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7 
  # Data manipulation
  - pandas=2.1.4   
  - numpy=1.26.3  
  - pyarrow=11.0.0 
  # ML
  - scikit-learn=1.2.2 
  - xgboost
  - gensim=4.3.0       
  - shap
  - umap-learn
  - transformers=4.32.1 
  - sentence-transformers
  - pytorch
  - bertopic
  - scipy     
  # Visualization
  - matplotlib=3.8.0 
  - matplotlib-venn  
  - seaborn=0.12.2   
  - wordcloud
  - ipython=8.20.0  
  - ipywidgets=8.0.4 
  - venn
  # NLP
  - nltk=3.8.1       
  - spacy
  - langdetect
  - emoji
  - sentencepiece
  # Graph / network
  - networkx=3.1     
  # Utilities
  - tqdm=4.65.0      
  - tabulate
  - statsmodels
  - ruptures
  - ipykernel=6.28.0 
  - papermill
  # - pip:
  #   - bertopic



################ How to use? In terminal do: ################
# conda env create -y -f ./config/conda_requirements.yml
# conda activate backbone_env_v2
# python -m ipykernel install --user --name backbone_env_v2 --display-name "backbone_env_v2"
